global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
    
  - job_name: 'cadvisor'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8088
      
  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
      
  - job_name: 'notification'
    metrics_path: '/notification/mgmt-notification/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.16.15.18:8282']
    basic_auth:
      username: 'mgmt'
      password: 'mgmtadmin'
      
  - job_name: 'backpack'
    metrics_path: '/inscricao/mgmt-backpack/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.16.15.18:8181']
    basic_auth:
      username: 'mgmt'
      password: 'mgmtadmin'